### ROI de uma Imagem:
Um conceito importante em processamento de imagens é a Região de Interesse. Entede-se como Região de Interesse (ROI - "Region Of Interest" ou AOI "Area Of Interest") a região obtida de maneira automática ou a partir da interação de um usuário onde o processamento estará totalmente concentrado. 

##### Objetivos:
    
        1. Obter um ROI de uma imagem a partir da área selecionada pelo mouse

In [2]:
import cv2 
import numpy as np

In [3]:
path = r'C:\Users\shuel\Documents\Workspace\computer-vision\computer-vision-meganha\005-basic-video-commands\images'
image = cv2.imread(path + '\lena.png')
image_to_show = np.copy(image)

In [4]:
# Estados iniciais do mouse
cropping = False
x_init, y_init, top_left_pt, bottom_right_pt = 0, 0, 0, 0

In [5]:
def roi(event, x, y, flags, param):
    global image_to_show, x_init, y_init, top_left_pt, bottom_right_pt, cropping

    if event == cv2.EVENT_LBUTTONDOWN:
        cropping = True
        x_init, y_init = x,y
        image_to_show = np.copy(image)
        print(f'Ponto inicial em X {x_init}')
        print(f'Ponto inicial em Y {y_init}')

    elif event == cv2.EVENT_MOUSEMOVE:
        if cropping == True:
            image_to_show = np.copy(image)
            cv2.rectangle(image_to_show, (x_init, y_init), (x, y), (0, 255, 0), 1)
    
    elif event == cv2.EVENT_LBUTTONUP:
        cropping = False
        top_left_pt, bottom_right_pt = x,y
        print(f'Ponto superior {top_left_pt}')
        print(f'Ponto superior {bottom_right_pt}')

cv2.namedWindow('image')
cv2.setMouseCallback('image', roi)

while True:

    cv2.imshow('image', image_to_show)
    k = cv2.waitKey(1)

    if k == ord('c'): # Cortar a área de interesse
        if y_init > bottom_right_pt:
            y_init, bottom_right_pt = bottom_right_pt, y_init
        
        elif x_init > top_left_pt:
            x_init, top_left_pt = top_left_pt, x_init

        elif bottom_right_pt - y_init > 1 and top_left_pt - x_init > 0:
            image = image[y_init:bottom_right_pt, x_init:top_left_pt]
            print(image)
            image_to_show = np.copy(image)

    elif k == ord('s'): # Salvar a imagem
        cv2.imwrite('teste.jpg', image_to_show)

    elif cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()
        
   

Ponto inicial em X 375
Ponto inicial em Y 189
Ponto superior 205
Ponto superior 392
Ponto inicial em X 308
Ponto inicial em Y 242
Ponto superior 308
Ponto superior 242
Ponto inicial em X 371
Ponto inicial em Y 195
Ponto superior 188
Ponto superior 399
[[[122 104 191]
  [121 109 194]
  [111 100 191]
  ...
  [116 142 231]
  [121 143 232]
  [120 143 229]]

 [[122 104 170]
  [107  88 173]
  [ 97  69 152]
  ...
  [116 144 231]
  [117 147 230]
  [119 144 231]]

 [[111 107 194]
  [110  99 183]
  [116  92 167]
  ...
  [119 145 231]
  [113 139 232]
  [118 148 232]]

 ...

 [[ 69  34 100]
  [ 78  49 127]
  [ 83  69 141]
  ...
  [ 73  40 130]
  [ 70  36 122]
  [ 82  53 128]]

 [[ 64  31  98]
  [ 77  61 133]
  [ 78  58 140]
  ...
  [ 67  38 126]
  [ 65  38 124]
  [ 68  41 126]]

 [[ 63  30 103]
  [ 70  60 140]
  [ 87  66 143]
  ...
  [ 61  35 123]
  [ 73  45 130]
  [ 75  47 130]]]
Ponto inicial em X 50
Ponto inicial em Y 40
Ponto superior 50
Ponto superior 40
Ponto inicial em X 35
Ponto inicial em