## Ajuste de escala
A operação de ajuste de escala tem como objetivo alterar proporcionalmente as dimensões de uma imagem sem que a mesma fique distorcida 

Imports

In [1]:
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt

Lendo a imagem

In [2]:
path = r'C:\Users\shuel\Documents\Workspace\computer-vision\computer-vision-meganha\001-pre-processing\images\einstein.jpg'
imgOriginal = cv.imread(path)

In [3]:
print(imgOriginal)

[[[ 69  69  69]
  [ 66  66  66]
  [ 65  65  65]
  ...
  [ 34  34  34]
  [ 33  33  33]
  [ 34  34  34]]

 [[ 67  67  67]
  [ 64  64  64]
  [ 64  64  64]
  ...
  [ 29  29  29]
  [ 29  29  29]
  [ 30  30  30]]

 [[ 71  71  71]
  [ 68  68  68]
  [ 67  67  67]
  ...
  [ 27  27  27]
  [ 27  27  27]
  [ 28  28  28]]

 ...

 [[ 31  31  31]
  [ 28  28  28]
  [ 26  26  26]
  ...
  [253 253 253]
  [252 252 252]
  [255 255 255]]

 [[ 30  30  30]
  [ 28  28  28]
  [ 26  26  26]
  ...
  [253 253 253]
  [255 255 255]
  [255 255 255]]

 [[ 31  31  31]
  [ 28  28  28]
  [ 25  25  25]
  ...
  [253 253 253]
  [255 255 255]
  [254 254 254]]]


Função resize(src, dst, fx, fy, interpolation)

Entrada:

        1. src = Matriz referente a imagem
        2. dst = Imagem de saída
        3. fx = fator de escala horizontal
        4. fy = fator de escala vertical 
        5. interpolation = método de interpolação
            INTER_NEAREST
            INTER_LINEAR
            INTER_AREA
            INTER_CUBIC

Saída:
        
        1. Imagem modificada

In [4]:
imgModificada = cv.resize(imgOriginal, 
                         None, 
                         fx = 0.8,
                         fy = 0.8,
                         interpolation = cv.INTER_CUBIC)

In [5]:
cv.imshow("Imagem Original", imgOriginal)
cv.imshow("Imagem Modificada", imgModificada)
cv.waitKey(0)
cv.destroyAllWindows()